sasjs/core

base/mp_filtercheck.sas, base/mp_hashdataset.sas, base/mp_testservice.sas, tests/testinit.sas, tests/viya/mv_createwebservice.test.sas, tests/viya/mv_getjobresult.test.sas, viya/mv_getjobresult.sas
=> feat: new mv_getjobresult.sas macro, corresponding test, and additional fixes

base/mp_abort.sas
=> fix: adding sysvlong to mp_abort also

base/mp_abort.sas, base/mp_filtervalidate.sas, base/mp_jsonout.sas, tests/base/mp_filtervalidate.test.sas
=> Filter json fixes

all.sas, base/mp_testservice.sas, package.json, viya/mv_getjoblog.sas, viya/mv_getjobresult.sas, viya/mv_jobflow.sas
Updating mp_testservice.sas and mv_jobflow to use the provided context. Also updating mv_getjobresult to fetch byte by byte (as some inputs are very wide)
=> Context fixes on mv_jobflow and mp_testservice

all.sas, base/mp_ds2inserts.sas, base/mp_lib2inserts.sas
=> feat: supporting postgres timestamps for mp_ds2inserts and mp_lib2inserts

all.sas, base/mf_getuniquefileref.sas, base/mp_webin.sas, package-lock.json, package.json, tests/crossplatform/mf_getuniquefileref.test.sas, tests/crossplatform/mp_webin.test.sas
The `mp_webin()` macro provides consistency across SAS9 and Viya, and 1 vs multiple file inputs, when working with SAS web services, in terms of the _webin_xxx macro variables.  Documentation:  https://core.sasjs.io/mp__webin_8sas.html
This PR also includes a performance boost to the `mf_getuniquefileref()` macro.  Documentation:  https://core.sasjs.io/mf__getuniquefileref_8sas.html
Test results:
=> New mp_webin() macro and performance improvement to mf_getuniquefileref()

all.sas, base/mp_abort.sas, base/mp_appendfile.sas, base/mp_assertcolvals.sas, tests/crossplatform/mp_appendfile.test.sas
Documentation:  https://core.sasjs.io/mp__appendfile_8sas.html
Tests: https://core.sasjs.io/mp__appendfile_8test_8sas_source.html
=> feat: mp_appendfile macro for appending 2 or more files together

.all-contributorsrc, .npmignore, README.md, package-lock.json, package.json
add "all-contributors-cli" dependence to package.json
modify README.md file
=> docs: add all-contributors dependence

base/mp_zip.sas, tests/crossplatform/mp_zip.test.sas
Also adding 3 tests and updating the documentation.
=> fix: removing notes when running mp_zip, closes #88. .

all.sas, base/mp_lockanytable.sas, base/mp_lockfilecheck.sas, tests/crossplatform/mp_lockanytable.test.sas, tests/crossplatform/mp_lockfilecheck.test.sas, tests/testinit.sas
Docs:
* https://core.sasjs.io/mp__lockfilecheck_8sas.html
* https://core.sasjs.io/mp__lockanytable_8sas.html
Closes #93
=> Macros for locking / unlocking tables 

all.sas, base/mf_getquotedstr.sas, base/mp_getcols.sas, base/mp_init.sas, base/mp_makedata.sas, base/mp_reseterror.sas, base/mp_sortinplace.sas, tests/crossplatform/mp_init.test.sas, tests/crossplatform/mp_lib2inserts.test.sas, tests/crossplatform/mp_lockfilecheck.test.sas, tests/crossplatform/mp_reseterror.test.sas, tests/testinit.sas
New macros (mp_reseterror and mp_init), new datetime format added to mp_getcols, and stub prepared for mp_makedata
=> feat: new macros 

all.sas, base/mp_searchdata.sas, tests/crossplatform/mp_searchdata.test.sas
Also added tests and refreshed docs.  Closes #108
=> fix: rebuilding mp_searchdata into data step to avoid SQL warning. 

all.sas, base/mf_existfeature.sas, base/mf_getattrc.sas, base/mf_getattrn.sas, base/mf_mkdir.sas, base/mf_nobs.sas, base/mp_copyfolder.sas, base/mp_ds2fmtds.sas, base/mp_ds2inserts.sas, base/mp_filtervalidate.sas, base/mp_getconstraints.sas, base/mp_getddl.sas, base/mp_init.sas, base/mp_jsonout.sas, base/mp_lockanytable.sas, meta/mm_createwebservice.sas, tests/crossplatform/mp_ds2fmtds.test.sas, tests/viyaonly/mv_createwebservice.test.sas, viya/mv_createwebservice.sas, viya/mv_getfoldermembers.sas, viya/mv_jobwaitfor.sas
Also updated comments, documentation and tests.
=> feat: adding varinitchk=ERROR to mp_init.  Closes #110. 

all.sas, base/mf_getengine.sas, base/mp_applyformats.sas, base/mp_getformats.sas, base/mp_validatecol.sas, tests/crossplatform/mp_applyformats.test.sas, tests/crossplatform/mp_validatecol.test.sas
New features:
* new `mp_applyformats()` macro to apply a set of formats to 1 or more tables
* new test in mp_validatecol to confirm whether a provided format is syntactically valid
=> Applyformats

all.sas, base/mp_validatecol.sas, tests/crossplatform/mp_validatecol.test.sas
docs:  https://core.sasjs.io/mp__validatecol_8sas_source.html
=> feat: new validation (ISINT) in the mp_validatecol.sas macro

all.sas, base/mp_assertscope.sas, tests/crossplatform/mp_assert.test.sas, tests/crossplatform/mp_assertscope.test.sas
Also adding test for mp_assert.sas
=> feat: adding mp_assertscope.sas, closes #146. 

all.sas, base/mp_ds2csv.sas, base/mp_streamfile.sas
Also enforcing quotes around encoding option in mp_ds2csv
=> adding WOFF to mp_streamfile

all.sas, viya/mv_registerclient.sas
=> feat: adding consul_token option as parameter in mv_registerclient.  

README.md, base/mp_assertscope.sas, base/mp_lockanytable.sas, base/mp_streamfile.sas, meta/mm_assignlib.sas, sasjs/sasjsconfig.json, server/ms_createfile.sas, server/ms_runstp.sas, server/ms_webout.sas, tests/serveronly/mfs_httpheader.test.sas, tests/serveronly/ms_createfile.test.sas, tests/serveronly/ms_runstp.test.sas
Also releasing a set of macros for working with the sasjs/server apis
=> fix: updating mp_streamfile for sasjs/server compatibility

README.md, all.sas, base/mf_getuniquelibref.sas, base/mp_assertscope.sas, tests/crossplatform/mf_getuniquelibref.test.sas
Please consider this as a non-breaking replacement of the existing macro, although I'd be happy to learn how best to proceed when a breaking change cannot be avoided.
=> fix: Closes #182 - update to mf_getuniquelibref.sas

all.sas, base/mp_hashdataset.sas, base/mp_md5.sas
Credit to the eagle eyes of [FreelanceReinhard](https://communities.sas.com/t5/user/viewprofilepage/user-id/32733)!
=> fix: adding explicit $ sign to hex32. format in mp_md5() macro

all.sas, base/mp_dirlist.sas, tests/crossplatform/mp_dirlist.test.sas
=> fix: supporting empty dirs in mp_dirlist. Test updated.

all.sas, base/mp_getpk.sas, sasjs/sasjsconfig.json, tests/crossplatform/mp_getpk.test.sas
Also wrote two tests to cover the case where the index is simple or composite.
=> fix: ensuring indexes are picked up in mp_getpk().  Closes #212

all.sas, sasjs/sasjsconfig.json, server/ms_createuser.sas, server/ms_getusers.sas, tests/serveronly/ms_createuser.test.sas, tests/serveronly/ms_getusers.test.sas, tests/serveronly/ms_runstp.test.sas, tests/testinit.sas
Added:
* `ms_createuser()` - https://core.sasjs.io/ms__createuser_8sas.html
*  `ms_getusers()` - https://core.sasjs.io/ms__getusers_8sas.html
Also added tests for the above and fixed a failing test for `ms_runstp`
=> feat: ms_createuser macro

all.sas, base/mp_streamfile.sas
Correcting Content-type case issue also
Closes #227
=> feat: adding MARKDOWN support to `mp_streamfile()`

all.sas, ddl/mddl_sas_cntlout.sas
=> chore: fix typo in mddl_sas_cntlout.sas

all.sas, meta/mm_adduser2group.sas, sasjs/sasjsconfig.json, server/ms_adduser2group.sas, server/ms_getgroups.sas, server/ms_getusers.sas, tests/serveronly/ms_adduser2group.test.sas, tests/serveronly/ms_creategroup.test.sas, tests/serveronly/ms_createuser.test.sas, tests/serveronly/ms_getgroups.test.sas, tests/serveronly/ms_getusers.test.sas, tests/serveronly/ms_runstp.test.sas, tests/serveronly/ms_testservice.test.sas, tests/serveronly/ms_webout.test.sas
This PR updates ms_getgroups with a user filter, and ms_getusers with a group filter. ms_adduser2group was also created to faciliate the necessary test(s).
=> feat: enabling group macros on sasjs/server

PULL_REQUEST_TEMPLATE.md
- Add template for pull requests.
=> chore(template): added pull request template

.github/PULL_REQUEST_TEMPLATE.md, all.sas, base/mp_ds2cards.sas
Closes #261 
Support special missings in mp_ds2cards()
* Added a `missing` statement with all possible special missing values in mp_ds2cards
* Changed `base_ds` to positional for consistency with other `mp_ds2xxx()` macros (is backwards compatible)
* moved the PR template to the `.github` folder with other github related templates
=> fix: special missing support in mp_ds2cards()

all.sas, base/mp_binarycopy.sas
#277 
Allow conditional execution of mp_binarycopy
Added iftrue parameter
=> fix: iftrue parameter for mp_binarycopy.  Closes #277

all.sas, base/mf_increment.sas, tests/base/mf_increment.test.sas
n/a
Create a utility macro that increments a variable and returns the result
Created a new macro function - `mf_increment()` and corresponding test.
Docs are here:  https://core.sasjs.io/mf__increment_8sas.html
=> feat: new mf_increment macro

all.sas, base/mp_getddl.sas
Generated DDL in [data controller](https://datacontroller.io) was missing data set name
Ensures the dataset name is shown at the top in a comment
Moved the data step inside the do loop
=> fix: comment issue in DDL generation

all.sas, meta/mm_getstpinfo.sas
Closes #303 
Extracts various properties (eg serverContext, URI, first 32k bytes of code) from an STP
Extracted in a single datastep, no dependent macros
=> chore(lint): reduce length

all.sas, base/mp_gitreleaseinfo.sas, tests/base/mp_gitreleaseinfo.test.sas
n/a
Macro to fetch release info from a GIT repo provider
New macro - `mp_gitreleaseinfo.sas`
=> feat: new gitreleaseinfo macro and associated test

.sasjslint, all.sas, meta/mm_createwebservice.sas, server/ms_createwebservice.sas, server/ms_getgroups.sas
n/a
* increased length of `description` var to $256 from $64 in ms_getgroups
* added `noGremlins` option to sasjslint
* rebuilt the `all.sas` including previous ms_creatwebservice.sas fix
=> fix: increasing desc length to 256 in ms_getgroups

all.sas, meta/mm_createwebservice.sas
#325 
Prevent outdated macro definition appearing in mm_createwebservice.sas
Added maxobs param
=> fix: closes #325 by including maxobs param

all.sas, base/mp_chop.sas, base/mp_md5.sas, base/mp_storediffs.sas
Also updated some program headers to reflect new Data Controller pricing structure.  all.sas regenerated.
n/a
Increasing logging in mp_chop
Increased to 200 when debug enabled, also updated program headers
=> fix: increasing logging of mp_chop to 200 records when mdebug is enabled

.github/workflows/main.yml
n/a
run packages release after semantic release
changed order in main.yml
=> chore: packages release after semantic release

.github/workflows/main.yml, sasjs/utils/create_sas_package.sas
- Use `GITHUB_TOKEN` as an access token in github actions.
- Updated `.github/workflows/main.yml`.
- Updated `sasjs/utils/create_sas_package.sas`.
=> chore(github): fixed token

all.sas, base/mf_getuniquename.sas, base/mp_binarycopy.sas, base/mp_chop.sas, base/mp_cleancsv.sas, base/mp_createconstraints.sas, base/mp_ds2ddl.sas, base/mp_getcols.sas, base/mp_getddl.sas, base/mp_gsubfile.sas, base/mp_md5.sas, base/mp_prevobs.sas, base/mp_searchcols.sas, meta/mm_createapplication.sas, meta/mm_getservercontexts.sas, meta/mm_getusers.sas
Relates to #347 
Add additional missing tags
Missed some tags in the previous pr (#347) so added them here
=> chore: missing doc updates

.github/workflows/main.yml
=> chore: adding cli dependency

.git-hooks/pre-commit, .github/workflows/main.yml, .github/workflows/notmain.yml
=> chore: moving all.sas logic to another action

.github/workflows/main.yml, .github/workflows/notmain.yml
commenting vpn due to package issues
=> chore: Bumpfix

all.sas, meta/mm_assigndirectlib.sas
fix: error from %put when mdebug=0
What this PR intends to achieve.
What code changes have been made to achieve the intent.
- [x ] Code is formatted correctly (`sasjs lint`).
- [x ] Any new functionality has been unit tested.
- [x ] All unit tests are passing (`sasjs test`).
- [x ] `all.sas` has been regenerated (`python3 build.py`)
=> fixed error from %put message when mdebug=0

all.sas, base/mp_filtercheck.sas, tests/base/mp_filtercheck.test.sas
#368 
https://git.datacontroller.io/dc/dc/issues/68
Enables variable names as well as values in the filter macros
Update to filter checks
=> feat: enable filter by variable name in mp filter series

all.sas, meta/mm_getdetails.sas
=> chore(docs): header for mm_getdetails

all.sas, base/mp_getcols.sas
=> 385 support nldatm in mp getcols

README.md, all.sas
adding https://github.com/Criptic/sas_snippets
=> chore: readme

all.sas, base/mf_mimetype.sas, sasjs/sasjsconfig.json, tests/base/mf_mimetype.test.sas, tests/testinit.sas, tests/viyaonly/mfv_getpathuri.test.sas, tests/viyaonly/mv_createfile.test.sas, tests/viyaonly/mv_createfolder.test.sas, viya/mfv_getpathuri.sas, viya/mv_createfile.sas, viya/mv_createfolder.sas
closes #388 
Also adding mf_mimetype and mvf_getpathuri macros
=> updated create_file service

all.sas, viya/mv_createfile.sas, viya/mv_createfolder.sas, viya/mv_createwebservice.sas, viya/mv_deletefoldermember.sas, viya/mv_deletejes.sas
Relates to https://git.datacontroller.io/dc/dc/issues/156
=> fix: streamlining viya deploys

all.sas, viya/mv_createfile.sas, viya/mv_createwebservice.sas, viya/mv_deletejes.sas
geared towards:  https://git.datacontroller.io/dc/dc/issues/156
=> fix: ensuring svg rendering from SAS drive

all.sas, viya/mv_createfile.sas, viya/mv_createfolder.sas
further streamlining for https://git.datacontroller.io/dc/dc/issues/156
=> chore: removing put statements

all.sas, base/mp_replace.sas, tests/viyaonly/mv_createfile.test.sas, viya/mv_createfile.sas
Relates to https://github.com/sasjs/cli/issues/1403
=> feat: adding mp_replace option to mv_createfile

all.sas, viya/mv_createfile.sas
support png in streaming viya apps
=> fix: support png in streaming viya apps

all.sas, viya/mv_createfile.sas
relates to https://git.datacontroller.io/dc/dc/issues/156
=> fix: ff downloading instead of streaming html on viya

all.sas, tests/viyaonly/mfv_getfolderpath.test.sas, tests/viyaonly/mfv_getpathuri.test.sas, viya/mfv_getfolderpath.sas
+ associated test 
created to support the fix for https://git.datacontroller.io/dc/dc/issues/171
=> feat: new mfv_getfolderpath macro

all.sas, base/mp_replace.sas, viya/mv_createfolder.sas
=> fix: re-attempt of request, hopefully fixes #400
