sasjs/core

package-lock.json, package.json
Issue: 
Old CLI has invalid command to support windows CMD/Powershell
`prepare` in `package.json` has invalid syntax to support windows CMD/Powershell
Implementation: 
- Bumped latest `sasjs/cli`
- Change `prepare` command
=> fix: bump sasjs/cli version + 'prepare' support windows CMD/Powershell

base/mp_ds2inserts.sas, tests/base/mp_ds2inserts.test.sas
A new macro for creating SQL inserts.  Usage:
```sas
%mp_ds2inserts(sashelp.class,outref=myref,outds=class)
data class;
set sashelp.class;
stop;
proc sql;
%inc myref;
```
Generates (first 3 observations shown):
```
/* class (19 rows, 5 columns) */
insert into class set 
Name='Alfred'
,Sex='M'
,Age=14
,Height=69
,Weight=112.5
;
insert into class set 
Name='Alice'
,Sex='F'
,Age=13
,Height=56.5
,Weight=84
;
insert into class set 
Name='Barbara'
,Sex='F'
,Age=13
,Height=65.3
,Weight=98
;
```
A corresponding test was provided in mp_ds2inserts.test.sas
=> feat: mp_ds2inserts macro

base/mf_getapploc.sas, tests/base/mf_getapploc.test.sas
Creating a new `mf_getapploc` value to dynamically determine the location of backend tests, jobs and web services for a particular SASjs application
Docs:  https://core.sasjs.io/mf__getapploc_8sas.html
=> feat: new mf_getapploc macro

all.sas, base/mp_assertcolvals.sas, base/mp_getcols.sas, tests/crossplatform/mp_getcols.test.sas
This macro takes the `proc contents` output and "tidies it up" in the following ways:
* Blank labels are filled in with column names
* Formats are reconstructed with default values
* Types such as DATE / TIME / DATETIME are inferred from the formats
Documentation: https://core.sasjs.io/mp__getcols_8sas.html
Tests: https://core.sasjs.io/mp__getcols_8test_8sas.html
=> Mp getcols macro

.gitpod.yml, all.sas, base/mp_getconstraints.sas, sasjs/sasjsconfig.json, tests/crossplatform/mp_getconstraints.test.sas
Also added test: https://core.sasjs.io/mp__getconstraints_8test_8sas_source.html
Ran test manually (on SAS 9) due to Viya server outage.  
Closes #83
<a href="https://gitpod.io/#https://github.com/sasjs/core/pull/84"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: refactored mp_getconstraints due to apparent bug in dictionary.table_constraints

all.sas, base/mf_existds.sas, base/mf_getvalue.sas, base/mp_assertdsobs.sas, base/mp_dropmembers.sas, base/mp_getconstraints.sas, base/mp_getpk.sas, base/mp_setkeyvalue.sas, base/mp_sortinplace.sas, base/mp_unzip.sas, package-lock.json, package.json, sasjs/sasjsconfig.json, tests/crossplatform/mf_existds.test.sas, tests/crossplatform/mp_getpk.test.sas, tests/crossplatform/mp_sortinplace.test.sas
New macros:
* mp_getpk - grab the actual primary key from a table (will also consider a unique / not null constraint as a PK)
* mp_sortinplace - will perform a sort of an indexed SAS dataset, using the PK, without dropping the constraints
Updates:
* mp_getconstraints - refactored / streamlined, now also provides the order of columns within a constraint
* mp_unzip - updated to be more reliable when unzipping binary files
* mp_dropmembers - added an `iftrue` keyword parameter to enable prettier conditional drops at the end of utility macros
Also the header / documentation in several macros was updated.
=> Several new macros, and improvements to old ones

all.sas, base/mf_dedup.sas, tests/crossplatform/mf_dedup.test.sas
Full credit to [@scottbass](https://www.linkedin.com/in/scottbass) and his [dedup_mstring](https://github.com/scottbass/SAS/blob/master/Macro/dedup_mstring.sas) macro for inspiration.
Test cases:
```sas
%let str=One two one two and through and through;
%mp_assert(
iftrue=("%mf_dedup(&str)"="One two one and through"),
desc=Basic test,
outds=work.test_results
)
%mp_assert(
iftrue=("%mf_dedup(&str,outdlm=%str(,))"="One,two,one,and,through"),
desc=Outdlm test,
outds=work.test_results
)
```
=> `mf_dedup()` macro - removes duplicates from a macro string

.sasjslint, all.sas, base/mf_getfmtlist.sas, base/mf_getfmtname.sas, base/mf_getquotedstr.sas, base/mp_getformats.sas, base/mp_init.sas, base/mp_mdtablewrite.sas, base/mp_sortinplace.sas, base/mp_storediffs.sas, meta/mm_getstps.sas, tests/crossplatform/mf_getfmtlist.test.sas, tests/crossplatform/mf_getfmtname.test.sas, tests/crossplatform/mp_getformats.test.sas, tests/crossplatform/mp_init.test.sas, tests/crossplatform/mp_sortinplace.test.sas, tests/crossplatform/mp_storediffs.test.sas
New macros:
* mf_getfmtname() -> converts a format (eg comma12.2) to the format name (eg COMMA)
* mf_getfmtlist() -> returns a distinct list of format NAMES (see above) from a dataset
* mp_getformats() -> exports the format definitions of all the formats applied to a table, or a straight list of formats
Modified macros:
* mp_init() - added `ls=max` and `%let sasjswork=%sysfunc(pathname(work));` as a global variable
=> More Macros

all.sas, base/mp_ds2md.sas, base/mp_getformats.sas, base/mp_makedata.sas, sasjs/sasjsconfig.json, tests/crossplatform/mp_ds2md.test.sas
Also modified the parameter from fref to outref.  This makes it more consistent with the other mp_ds2xx range of macros.
The data values are now wrapped in `backticks` to prevent autoformatting and avoid merged cells.
=> BREAKING CHANGE: renamed mp_mdtablewrite.sas to mp_ds2md.sas

all.sas, base/mf_islibds.sas, base/mp_makedata.sas, tests/crossplatform/mf_islibds.test.sas
* mf_islibds() macro to test if a library.dataset reference is syntactically valid
* mf_makedata() now respects primary keys and is built deterministically to enable joins to other tables
=> feat: mf_islibds() macro to test if a library.dataset reference is valid

all.sas, base/mp_makedata.sas, tests/crossplatform/mp_makedata.test.sas
fix: enabling makedata support for charvars > $32 and tables without primary keys.  Also added tests.
=> `mp_makedata()` improvements

all.sas, base/mp_coretable.sas, base/mp_filterstore.sas, base/mp_lockanytable.sas, base/mp_retainedkey.sas, tests/crossplatform/mp_coretable.test.sas, tests/crossplatform/mp_filterstore.test.sas
Two macros (and corresponding tests) added in this release:
* mp_filterstore.sas -> Used to store an input filter table to a permanent location (returning a retained key) for use in saved filters:  https://core.sasjs.io/mp__filterstore_8sas.html
* mp_coretable.sas -> Single macro to handle the table management (now that we have multiple macros that depend on permanent tables):  https://core.sasjs.io/mp__coretable_8sas.html
=> feat: mp_filterstore macro

all.sas, base/mp_cntlout.sas, base/mp_getformats.sas, base/mp_loadformat.sas, base/mp_lockanytable.sas, base/mp_lockfilecheck.sas, base/mp_storediffs.sas, tests/crossplatform/mp_cntlout.test.sas, tests/crossplatform/mp_stackdiffs.test.sas
`mp_cntlout()` provides a consistent way to export formats from a format catalog (start / end left-aligned for numeric lookups, and lengths set to maximums rather than the format content maximums).
Updates to the rest of the framework to support the `-FC` suffix approach for identifying format catlogs in a libds.
=> feat: new mp_cntlout.sas macro

all.sas, base/mf_getuser.sas, base/mp_loadformat.sas, tests/crossplatform/mp_loadformat.test.sas
Adding test  also.  Closes #190
Also quoting `mf_getuser` in case of commas.  Closes #189
=> fix: ensuring audit table gets loaded in mp_loadformat.

all.sas, base/mp_streamfile.sas
when `mp_streamfile` is used on all platforms
=> fix: send html as attachment rather than streamed content

all.sas, base/mp_abort.sas
#267 
Avoid the use of `endsas;` in 9.4m6+ environments - an invalid response is better than no response.
Removed endsas from mp_abort() in this circumstance
=> fix: removing endsas for 9.4m6+ WIN enviornments in mp_abort

all.sas, base/mf_existfeature.sas, base/mp_getpk.sas
n/a
Cross compatibility of mp_getpk in different runtimes
Checked runtime before selecting `dbms_memtype`
=> fix: enabling cross-compatibility of mp_getpk macro

all.sas, base/mp_storediffs.sas
Closes #281
#281
Set static length for `_label_`, to both ensure it exists, and also to avoid length warnings
length statement, drop statement, call missing
=> fix: prevent warning from `_label_` variable with different lengths

all.sas, base/mp_getconstraints.sas
Closes #283
#283
Prevent exception errors when querying dictionary.column_constraints
used a case sensitive search query - sacrificing accuracy for stability & consistency
=> fix: avoid exceptions from dictionary.table_constraints.

all.sas, base/mp_cleancsv.sas, tests/base/mp_cleancsv.test.sas
#289 
Ensure that lines with blank rows for CR-formatted files are correctly converted to CRLF
Made use of a goto statement (seemed appropriate in this context)
=> fix: enable embedded blanks in mp_cleancsv, closes #289

.gitignore, all.sas, base/mf_getgitbranch.sas, base/mf_readfile.sas, base/mp_gitlog.sas, base/mp_gitstatus.sas, tests/base/mf_getgitbranch.test.sas, tests/base/mf_readfile.test.sas, tests/base/mp_gitlog.test.sas
n/a
Creation of three new macros to enable interactive GIT information in a SASjs Web App
Created the following macros (and corresponding tests / documentation):
* mf_readfile.sas macro function
* mf_getgitbranch.sas macro function
* mp_gitlog.sas macro procedure
=> 3 new macros (and tests) for the core library

all.sas, base/mf_existvar.sas, base/mp_lockanytable.sas, tests/base/mf_existvar.test.sas, tests/base/mp_getcols.test.sas
n/a
Fixing some recently discovered bugs
Updates to:
* mf_existvar.sas
* mp_lockanytable.sas
A test is also included to cover the change in mf_existvar.sas
=> fix: invalid macro variable in mp_lockanytable.sas

all.sas, meta/mm_createstp.sas
Closes #350
Enable choice of LogicalServerType.  Needs to be integrated with the SASjs CLI at some point.  For now, if you wish to use this in the `sasjs build` command (to create STPs on the Workspace Server), just modify the default value and add the macro to your project macros.  When you compile, the CLI will use the project copy in the compiled build program.
Added an option to change LogicalServerType in mm_createstp.sas
=> feat: adding LogicalServerType option to mm_createstp.sas macro. 

all.sas, base/mp_validatecol.sas
https://git.datacontroller.io/dc/dc/issues/50
Removed a UTF 8 char so that it does not disrupt LATIN9 App Servers in certain specific situations
Changed Søren Lassen's first name to Soren (we hope you forgive us)
=> fix: removing UTF 8 char to support LATIN9 environments

.github/workflows/main.yml
n/a
Bumping release by updating build.yaml
added a step to auto-generate the all.sas
also bumped semantic release and checkout actions to v4
=> fix: bumping semantic release and checkout actions to v4

all.sas, base/mf_isblank.sas
This commit adds macro trigger to mf_isblank usage example.
Link any related issue(s) in this section.
Current usage example doesn't invoke the macro.
What code changes have been made to achieve the intent.
=> Add macro trigger to usage example

all.sas, base/mp_stackdiffs.sas, base/mp_storediffs.sas, base/mp_stripdiffs.sas, meta/mm_getgroups.sas, tests/base/mp_stripdiffs.test.sas
#373 
Enable data history restoration, linked to https://git.datacontroller.io/dc/dc/issues/84
Created new mp_stripdiffs macro which reverses changes using the data audit table
=> feat: mp_stripdiffs macro - closes #373

all.sas, meta/mm_assigndirectlib.sas
#375 
enable open passthrough to take place
added logic to ensure that the macro is not prematurely exited
=> fix: logic in mm_assigdirectlib to close #375
